version: "3.8"

services:
  api:
    container_name: "api"
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
  client:
    container_name: "client"
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
  db:
    container_name: "db"
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - db-data:/var/lib/postgresql/data/
  data:
    container_name: "data"
    depends_on:
      - db
    build: ./data

volumes:
  db-data:
